In [13]:
import pandas as pd
import numpy as np
import folium
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [11]:
df_venues_raw = pd.read_pickle('app_ldn_venues_raw.pkl')
df_rent = pd.read_pickle('app_ldn_rent.pkl')
ldn_geojson = 'london_boroughs_proper.geojson'
df_groups_norm = pd.read_pickle('app_ldn_groups_norm.pkl')

In [12]:
df_groups_norm

,Borough,Eating out,Entertainment,Going out,Green spaces,Groceries,Health and Sports,Other,Public Transport,Shopping
0,Barking and Dagenham,0.209150,0.058824,0.058824,0.091503,0.091503,0.078431,0.163399,0.071895,0.176471
1,Barnet,0.414861,0.018576,0.066563,0.068111,0.061920,0.061920,0.078947,0.037152,0.191950
2,Bexley,0.296578,0.022814,0.121673,0.034221,0.079848,0.053232,0.098859,0.045627,0.247148
3,Brent,0.400802,0.022044,0.082164,0.054108,0.058116,0.042084,0.080160,0.058116,0.202405
4,Bromley,0.303435,0.028626,0.127863,0.085878,0.051527,0.070611,0.110687,0.055344,0.166031
5,Camden,0.452893,0.059504,0.125620,0.057851,0.082645,0.046281,0.066116,0.006612,0.102479
6,City of London,0.420635,0.063492,0.087302,0.063492,0.023810,0.119048,0.190476,0.000000,0.031746
7,Croydon,0.347826,0.014493,0.078675,0.072464,0.049689,0.053830,0.159420,0.053830,0.169772
8,Ealing,0.406137,0.032491,0.093863,0.063177,0.055957,0.061372,0.090253,0.054152,0.142599
9,Enfield,0.345114,0.024948,0.089397,0.076923,0.066528,0.064449,0.072765,0.054054,0.205821
10,Greenwich,0.278119,0.044990,0.118609,0.083845,0.059305,0.053170,0.114519,0.053170,0.194274
11,Hackney,0.410526,0.027368,0.197895,0.065263,0.067368,0.044211,0.075789,0.010526,0.101053
12,Hammersmith and Fulham,0.444444,0.033333,0.151111,0.062222,0.055556,0.064444,0.046667,0.002222,0.140000
13,Haringey,0.385965,0.029240,0.136452,0.074074,0.072125,0.054581,0.068226,0.048733,0.130604
14,Harrow,0.434932,0.017123,0.089041,0.071918,0.068493,0.085616,0.061644,0.034247,0.136986
15,Havering,0.287879,0.018182,0.093939,0.093939,0.069697,0.042424,0.130303,0.045455,0.218182
16,Hillingdon,0.282750,0.011673,0.099870,0.044099,0.037613,0.051881,0.228275,0.049287,0.194553
17,Hounslow,0.375681,0.014519,0.098004,0.052632,0.059891,0.050817,0.114338,0.049002,0.185118
18,Islington,0.504464,0.040179,0.185268,0.046875,0.044643,0.060268,0.022321,0.006696,0.089286
19,Kensington and Chelsea,0.435039,0.055118,0.090551,0.049213,0.068898,0.055118,0.088583,0.001969,0.155512
20,Kingston upon Thames,0.381333,0.037333,0.093333,0.106667,0.058667,0.050667,0.072000,0.037333,0.162667
21,Lambeth,0.403698,0.061633,0.161787,0.050847,0.058552,0.057011,0.073960,0.021572,0.110940
22,Lewisham,0.351129,0.020534,0.133470,0.065708,0.065708,0.039014,0.092402,0.049281,0.182752
23,Merton,0.371007,0.022113,0.078624,0.071253,0.066339,0.098280,0.071253,0.061425,0.159705
24,Newham,0.298901,0.021978,0.074725,0.054945,0.057143,0.063736,0.164835,0.061538,0.202198
25,Redbridge,0.372014,0.020478,0.092150,0.071672,0.075085,0.071672,0.078498,0.047782,0.170648
26,Richmond upon Thames,0.350440,0.033724,0.151026,0.133431,0.052786,0.067449,0.087977,0.029326,0.093842
27,Southwark,0.372372,0.049550,0.163664,0.058559,0.048048,0.054054,0.096096,0.022523,0.135135
28,Sutton,0.290640,0.014778,0.098522,0.118227,0.073892,0.068966,0.078818,0.059113,0.197044
29,Tower Hamlets,0.386824,0.054054,0.138514,0.074324,0.045608,0.064189,0.118243,0.023649,0.094595
30,Waltham Forest,0.362606,0.028329,0.133144,0.073654,0.062323,0.067989,0.073654,0.022663,0.175637
31,Wandsworth,0.440225,0.015471,0.167370,0.032349,0.061885,0.053446,0.061885,0.030942,0.136428
32,Westminster,0.377614,0.075031,0.119311,0.056581,0.046740,0.050431,0.152522,0.001230,0.120541

In [5]:
grps = df_groups_norm.columns[1:].tolist()

In [9]:
{grp: 0 for grp in grps}

{'Eating out': 0,
 'Entertainment': 0,
 'Going out': 0,
 'Green spaces': 0,
 'Groceries': 0,
 'Health and Sports': 0,
 'Other': 0,
 'Public Transport': 0,
 'Shopping': 0}

In [18]:
ALL_VENUES = df_venues_raw.copy()
LONDON_GEOJSON = ldn_geojson
LONDON = [51.5074, -0.1278]

ALLOWED_ACM_TYPES = df_rent['Category'].unique().tolist()
ALLOWED_GROUPS = df_groups_norm.columns.tolist()[1:]

In [13]:
def filter_rent_data(df=df_rent, categories=None, rent_range=None):
    """
    Returns boroughs that satisfy the conditions for `categories` and `rent_range`
        
    Inputs:
        df - pandas DataFrame containing rent data -> !!! Assumes df_rent as default 
        categories - an iterable or a string specifying appropriate accommodation types
        rent_range - a list or a tuple with r_min and r_max rent ranges.
        
    Output:
        boroughs - a list of boroughs that match the condition
    
    """
    if isinstance(categories, str):
        cats = [categories]
    else:
        cats = categories
    
    cat_cond = df['Category'].isin(cats)
    rent_lower = rent_range[0]
    rent_higher = rent_range[1]
    
    # If invalid data provided
    if rent_lower > rent_higher:
        rent_higher = rent_lower
    
    rent_cond_1 = (df['Lower quartile'] <= rent_higher) & (df['Upper quartile'] >= rent_higher)
    rent_cond_2 = (df['Lower quartile'] <= rent_lower) & (df['Upper quartile'] >= rent_lower)
    rent_cond = rent_cond_1 | rent_cond_2
    rent_cond = (df['Lower quartile'] <= rent_higher) & (df['Upper quartile'] >= rent_lower)
    
    not_null = ~df['Median'].isnull()

    df_filtered = df.loc[(cat_cond & rent_cond & not_null)]
    
    boroughs = df_filtered['Borough'].unique().tolist()
   
    return boroughs

def create_preferences(ranking=None):
    "Converts `ranking` list to normalized pandas DataFrame"
    pref_dict = {
        'Eating out': 0,
        'Entertainment': 0,
        'Green spaces': 0,
        'Groceries': 0,
        'Health and Sports': 0,
        'Nightlife': 0,
        'Other': 0,
        'Public Transport': 0,
        'Shopping': 0,
    }
    
    N = len(ranking)
    
    for i, cat in enumerate(ranking): 
        pref_dict[cat] = N - i
    
    df = pd.DataFrame.from_dict(pref_dict, orient='index', columns=['Preference'])
    df['Preference'] = df['Preference'] / df['Preference'].sum()
    
    return df

def recommend_boroughs(W=df_groups_norm, p=None, n_brghs=5):
    """
    Calculates matrix product of DataFrames W and p
    
    Inputs:
        W - pandas DataFrame containing venue group density for each borough
        p - pandas DataFrame with user group preferences
        n_brghs - int, number of boroughs to recommend
    
    Returns:
        rec_boroughs - `n_brghs` number of boroughs by highest match value
        df_rec - resulting recommendation matrix as pandas DataFrame
    
    """
    W_ = W.copy()
    W_.set_index(['Borough'], inplace=True)
    df_rec = (p['Preference'] * W_).sum(axis=1).to_frame()
    df_rec.columns = ['Match']
    df_rec.sort_values(by='Match', ascending=False, inplace=True)
    rec_boroughs = df_rec.head(n_brghs).index.tolist()

    return rec_boroughs, df_rec


def recommend_and_plot(df_groups, df_rent, rent_range=None, acm_type=None, ranking=None, n=5):
    """
    Recommends top n venues and plots the results on the map
    
    """
    available_boroughs = filter_rent_data(df=df_rent, categories=acm_type, rent_range=rent_range)
    p = create_preferences(ranking=ranking)
    df_grp_filtered = df_groups.loc[df_groups['Borough'].isin(available_boroughs)]
    rec_boroughs, df_rec = recommend_boroughs(W=df_grp_filtered, p=p, n_brghs=n)
    
    
    df_rec.reset_index(inplace=True)
    
    df_all = ALL_VENUES.copy()
    df_matched = df_all.loc[(df_all['Borough'].isin(rec_boroughs)) & (df_all['Group'].isin(ranking))]
    
    print('='*80)
    print('= Recommended boroughs based on your preferences')
    print('='*80)
    
    for i, b in enumerate(rec_boroughs):
        print(f"#{i+1}: {b}")
    print('='*80)
    print('= Plotting venues...')
                                                                     
                             
    # Plotting
    map_rec = folium.Map(location=LONDON, tiles='cartodbpositron', zoom_start=10)

    # Chloropleth Map of boundaries, where shading is dependent on median rent for 'All categories'
    folium.Choropleth(
        geo_data=LONDON_GEOJSON,
        fill_color='BuPu',
        data=df_rec,
        columns=['Borough', 'Match'],
        key_on='feature.properties.name',
        weight=1,
        line_color='black',
        fill_opacity=0,
        line_opacity=0.5,
        highlight=True,
    ).add_to(map_rec)  

    df_boroughs = df_matched[['Borough', 'BoroughLat', 'BoroughLon']].drop_duplicates()
                             
    # Add borough markers to map
    for i, row in df_boroughs.iterrows():
        borough = row['Borough']
        coords = [row['BoroughLat'], row['BoroughLon']]
        rent_pref = f"{rent_range[0]} - {rent_range[1]}"
        lbl_str = f"{borough} ({rent_pref}\\xA3)" # create a label with borough name and rent range

        label = folium.Popup(lbl_str, parse_html=True) # so that the label is used as a Popup

        # Add the marker
        folium.CircleMarker(
            coords,
            radius=10,
            popup=label,
            color='black',
            weight=1,
            fill=True,
            fill_color='black',
            fill_opacity=0.75,
            parse_html=False,
        ).add_to(map_rec)  

    color_map = {
        'Eating out': '#e41a1c',
        'Entertainment': '#377eb8',
        'Going out': '#ffff33',
        'Green spaces': '#984ea3',
        'Groceries': '#ff7f00',
        'Health and Sports': '#4daf4a',
        'Other': '#999999',
        'Public Transport': '#a65628' ,
        'Shopping': '#f781bf',
    }

    for i, row in df_matched.iterrows():
#         # let's plot only every 5th point
#         if i % 10 == 0:
#             continue
        lat_i = row['Venue Latitude']
        lon_i = row['Venue Longitude']
        venue = row['Venue']
        group = row['Group']

        label = f"{venue} ({group})"

        coords = [lat_i, lon_i]
        folium.CircleMarker(
            coords,
            radius=4,
            popup=label,
            color='black',
            weight=1,
            fill=True,
            fill_color=color_map[group],
            fill_opacity=0.9,
            parse_html=False).add_to(map_rec)

    return map_rec

In [21]:
# Interactive stuff starts here!